# Generated by Django 4.1.5 on 2023-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdb',
            name='image',
        ),
        migrations.AddField(
            model_name='projectdb',
            name='gitLink',
            field=models.URLField(default='https://'),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='imageLink',
            field=models.URLField(default='https://'),
        ),
        migrations.AlterField(
            model_name='projectdb',
            name='description',
            field=models.TextField(default='description', max_length=255),
        ),
    ]
